export default function RecipientCard({ recipient }) {
  if (!recipient) {
    return (
      <div className="mt-6 rounded-2xl border border-dashed border-white/20 bg-white/5 px-6 py-8 text-center text-sm text-slate-400">
        Assignments will appear here once generated by the admin team.
      </div>
    );
  }

  return (
    <div className="mt-6 space-y-4 rounded-2xl border border-white/10 bg-white/5 px-6 py-7 text-sm text-slate-200 shadow-soft">
      <h2 className="text-lg font-semibold text-white">Your recipient</h2>
      <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Keep it festive · Keep it secret</p>
      <div className="space-y-2 text-sm">
        <div>
          <span className="font-medium text-white">Name:</span> {recipient.name}
        </div>
        <div>
          <span className="font-medium text-white">Email:</span> {recipient.email}
        </div>
        <div>
          <span className="font-medium text-white">Wishlist:</span>
          <ul className="mt-2 list-disc pl-5 text-slate-300">
            {recipient.wishlist?.length ? recipient.wishlist.map((item, idx) => <li key={idx}>{item}</li>) : <li>No wishlist provided yet.</li>}
          </ul>
        </div>
      </div>
    </div>
  );
}
